repos:
#- repo: https://github.com/pycqa/pylint
#  rev: v2.17.4
#  hooks:
#  - id: pylint
- repo: local
  hooks:
  - id: test
    name: test
    language: python
    entry: pipenv run test
    pass_filenames: false
    verbose: true
  - id: lint
    name: lint
    language: system
    entry: pipenv run lint
    pass_filenames: false
